### authentication test 

### 1. Register Admin Baru
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "role_id": 1,
  "name": "Admin Klinik",
  "username": "admin",
  "password": "password123"
}

### 2. Test Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password123"
}


### Middleware Test

### 3. Test Akses Profil Tanpa Token (Harus Gagal 401)
GET http://localhost:5000/api/auth/profile

### 4. Test Akses Profil Dengan Token (Harus Berhasil 200 OK)
# Tempelkan token JWT hasil login kamu tepat setelah kata Bearer
GET http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxNjYzNiwiZXhwIjoxNzg1NTAzMDM2fQ.iNEONS3a-vQY9_KziOSYrwadN3yMcnn3aMLip9PNcmM


### Patients Endpoint Test

### 5. Tambah Pasien Baru
POST http://localhost:5000/api/patients
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

{
  "nik": "3201123456780001",
  "name": "Budi Santoso",
  "birth_date": "1990-05-15",
  "gender": "L",
  "address": "Jl. Merdeka No. 123, Bandung",
  "phone": "081234567890"
}

### 6. Ambil Semua Pasien
GET http://localhost:5000/api/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

### 7. Ambil Detail Pasien Berdasarkan ID
GET http://localhost:5000/api/patients/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

### 8. Update Data Pasien
PUT http://localhost:5000/api/patients/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

{
  "nik": "3201123456780001",
  "name": "Budi Santoso, S.Kom",
  "birth_date": "1990-05-15",
  "gender": "L",
  "address": "Jl. Merdeka No. 123, Bandung (Alamat Baru)",
  "phone": "081234567899"
}

### 9. Hapus Pasien
DELETE http://localhost:5000/api/patients/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc


### Registrations Endpoint Test

### 10. Buat Pendaftaran Pasien Baru
POST http://localhost:5000/api/registrations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

{
  "patient_id": 1,
  "doctor_id": 1,
  "polyclinic_id": 1,
  "visit_date": "2026-07-30",
  "payment_type": "BPJS",
  "initial_complaint": "Pusing pala ku dok."
}

### 11. Get Semua Pendaftaran Pasien
GET http://localhost:5000/api/registrations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc


### 12. Ubah Status Pendaftaran Pasien
PUT http://localhost:5000/api/registrations/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc


{
  "status": "Check In"
}


### Medcal Records Endpoint Test

### 13. Simpan Rekam Medis Pasien
POST http://localhost:5000/api/medical-records
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

{
  "registration_id": 3,
  "patient_id": 1,
  "doctor_id": 1,
  "subjective": "Pasien mengeluh pusing dan demam sejak kemarin.",
  "systolic": 120,
  "diastolic": 80,
  "body_temperature": 38.5,
  "weight": 65,
  "height": 170,
  "assessment": "Febris / Demam Dengue",
  "plan": "Paracetamol 500mg 3x1, istirahat cukup, minum air putih 2L per hari."
}

### 14. Ambil Riwayat Rekam Medis Pasien ID 1
GET http://localhost:5000/api/medical-records/patient/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc


### Queues Endpoint Test

### 15. Generate Nomor Antrean Baru
POST http://localhost:5000/api/queues
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

{
  "registration_id": 3
}

### 16. Lihat Daftar Antrean Hari Ini
GET http://localhost:5000/api/queues
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

### 17. Memanggil Status Antrean
PUT http://localhost:5000/api/queues/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJBZG1pbiIsImlhdCI6MTc4NTQxODUwNSwiZXhwIjoxNzg1NTA0OTA1fQ.T7TdTpkJ_02D7iwPvgtPVhqotse2HJENiXiBAKdAeIc

{
  "status": "Dipanggil"
}